### ISSUE TITLE
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access

### ISSUE THREAD

**Issue by asmarcz** [dafny-lang/dafny#4354] opened 2023-07-28 22:22 UTC
### Dafny version

4.2.0.0

### Code to produce this issue

```dafny
method Main(){
  print "Hello, World!\n";
}
```

### Command to run and resulting output

```code
Dafny encountered an internal error. Please report it at <https://github.com/dafny-lang/dafny/issues>.
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Microsoft.Dafny.VisibilityScope.VisibleInScope(VisibilityScope other)
   at Microsoft.Dafny.Declaration.IsRevealedInScope(VisibilityScope scope)
   at Microsoft.Dafny.Declaration.IsVisibleInScope(VisibilityScope scope)
   at Microsoft.Dafny.Translator.InVerificationScope(Declaration d)
   at Microsoft.Dafny.Translator.AddWellformednessCheck(RedirectingTypeDecl decl)
   at Microsoft.Dafny.Translator.AddTypeDecl(SubsetTypeDecl dd)
   at Microsoft.Dafny.Translator.DoTranslation(Program p, ModuleDefinition forModule)
   at Microsoft.Dafny.Translator.Translate(Program p, ErrorReporter reporter, TranslatorFlags flags)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Dafny.LanguageServer.Language.DafnyProgramVerifier.<>c__DisplayClass4_0.<GetVerificationTasksAsync>b__1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.Dafny.LanguageServer.Language.DafnyProgramVerifier.GetVerificationTasksAsync(CompilationAfterResolution compilation, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.CompilationManager.PrepareVerificationTasksAsync(CompilationAfterResolution loaded, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.CompilationManager.TranslateAsync()
```

### What happened?

Typed a hello world program, expected it to get verified.

### What type of operating system are you experiencing the problem on?

Linux

**Comment by keyboardDrummer** [comment] 2023-07-31 09:20
Did you get this exception in the IDE or on the CLI?

**Comment by harvey-challinor** [comment] 2023-07-31 14:37
I am also encountering this problem in the VS Code extension on windows.

**Comment by harvey-challinor** [comment] 2023-08-02 11:12
Unfortunately it seems very random, and I have not succeeded in reproducing it either

**Comment by keyboardDrummer** [comment] 2023-08-11 10:54
Since Dafny's language server is designed to only translate with 1 thread at a time, relevant source code [here](https://github.com/dafny-lang/dafny/blob/master/Source/DafnyLanguageServer/Language/DafnyProgramVerifier.cs#L40), I don't see how this problem could occur.

Maybe the concurrent modification is happening from another location than translation, but I'm not sure from where that would be since translation doesn't start until resolution is finished.

There could also be a bug in the caching logic that allows an uncloned declaration from one compilation to appear in another declaration, and then the resolution of version X+1 could collide with the still uncalled translation of version X.

All speculations, and without confirmation I don't feel comfortable making any changes :-) even though making turning [this dictionary](https://github.com/dafny-lang/dafny/blob/master/Source/DafnyCore/AST/VisibilityScope.cs#L28) into a concurrent one would resolve the crash at least.

**Comment by MikaelMayer** [comment] 2024-02-02 21:03
I think we fixed a few concurrent crashes so closing this issue until/if ever it pops up again

**Closed by MikaelMayer** 2024-02-02 21:03 UTC
Labels: kind: bug, severity: crash
