### ISSUE TITLE
Cannot put tests and Main in same file

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#3744] opened 2023-03-14 19:44 UTC
### Dafny version

4.0.0

### Code to produce this issue

```dafny
method {:test} Test() {
}
method Main() {
}
```

### Command to run and resulting output

```code
> dafny run thefile.dfy
(no problem)

> dafny test thefile.dfy
(0,-1): Error: Duplicate member name: Main
1 resolution/type errors detected in thefile.dfy
```

### What happened?

If I use `{:main}`, then the problem is also the same.

I should be able to run and test the file without compromise, like in Rust

### What type of operating system are you experiencing the problem on?

Windows

**Comment by davidcok** [comment] 2023-03-14 19:47
Duplicate of #3369

**Comment by davidcok** [comment] 2023-04-04 15:49
Implemented in PR 3769. Duplicate of 3221

**Closed by davidcok** 2023-04-04 15:49 UTC
Labels: kind: bug, part: resolver
