### ISSUE TITLE
resolver bug: opaque type on lefthand side of function in datatype

### ISSUE THREAD

**Issue by tjhance** [dafny-lang/dafny#1200] opened 2021-04-22 18:05 UTC
Pretty sure this is a bug. This file incorrectly gives a resolver error:

```
abstract module M {
  type T

  datatype Foo = Foo(func: T -> nat)
}
```

```
formal.dfy(4,27): Error: formal type parameter 'T' is not used according to its variance specification (it is used left of an arrow) (perhaps try declaring 'T' as '!T')
```

The error message mistakenly claims T is a formal type parameter. It's not generally illegal to use `T -> nat` or anything, I only see this error message in a `datatype` declaration.

**Comment by RustanLeino** [comment] 2021-04-22 23:29
This is indeed buggy behavior and I can reproduce it with Dafny 3.0.0. However, this seems to have been fixed in Dafny 3.1.0. Can you please confirm?

**Comment by tjhance** [comment] 2021-04-22 23:45
yes, my bad, it does work in 3.1

**Comment by RustanLeino** [comment] 2021-04-22 23:46
Yeah, the problem was that the opaque type `T` was treated as a type parameter, and to mention a type parameter is a negative position, as in `T -> nat`, you need to mark it was `!T`. This restriction does not apply to opaque types. PR https://github.com/dafny-lang/dafny/pull/1188 fixed the confusion between opaque types and type parameters, and thus also fixed this problem.

**Closed by RustanLeino** 2021-04-22 23:46 UTC
