### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by PrisionMike** [dafny-lang/dafny#2931] opened 2022-10-26 23:43 UTC
Compiler 3.9.0.41003 (Same Language Server)

Extension: 2.8.5

Platform: Windows VS Code 1.72.2

How to reproduce? Only occurs when opening this particular file:
```
method sumeva(A: array<int>) returns (E: int)
    requires a != null;
{
    var n := 0;
    var sum := 0;
    while( n < a.Length)
    decreases -n;
    {
        if (n%2 == 0)
        {
            sum := sum + a[n];
        }
        n := n + 1;
    }
}
```
Nothing else in the file. All other files work fine. But once this file is opened. I have to uninstall and reinstall the extension for the compiler to work again for any file. Till I reopen this file. Absolutely baffling.

Error:
```
Error - 1:41:41 am] Request textDocument/codeAction failed.
  Message: Internal Error - System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dafny.Resolver.SeqTypeArgToBeResolved.ToString()
   at Microsoft.Dafny.TypeConstraint.ErrorMsg.<Reporting>g__RemoveAmbiguity|5_0(Object[] msgArgs)
   at Microsoft.Dafny.TypeConstraint.ErrorMsg.Reporting(ErrorReporter reporter, String suffix)
   at Microsoft.Dafny.TypeConstraint.ReportErrors(ErrorReporter reporter)
   at Microsoft.Dafny.Resolver.SolveAllTypeConstraints()
   at Microsoft.Dafny.Resolver.ResolveTopLevelDecls_Core(List`1 declarations, Graph`1 datatypeDependencies, Graph`1 codatatypeDependencies, Boolean isAnExport)
   at Microsoft.Dafny.Resolver.ResolveProgram(Program prog)
   at Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver.RunDafnyResolver(TextDocumentItem document, Program program)
   at Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver.ResolveSymbols(TextDocumentItem textDocument, Program program, Boolean& canDoVerification, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.TextDocumentLoader.LoadInternal(DocumentTextBuffer textDocument, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.TextDocumentLoader.<>c__DisplayClass12_0.<<LoadAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Dafny.LanguageServer.Workspace.TextDocumentLoader.LoadAsync(DocumentTextBuffer textDocument, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.Compilation.ResolveAsync()
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentManager.GetLastDocumentAsync()
   at Microsoft.Dafny.LanguageServer.Handlers.DafnyCodeActionHandler.Handle(CodeActionParams request, CancellationToken cancellationToken)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|7_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token, ILogger logger)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token)
   at OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker.<>c__DisplayClass10_0.<<RouteRequest>b__5>d.MoveNext()
  Code: -32603
```

**Comment by keyboardDrummer** [comment] 2022-10-27 16:10
Duplicate of #2909

**Comment by alex-chew** [comment] 2022-10-27 16:59
Duplicate of https://github.com/dafny-lang/dafny/issues/2828

**Comment by atomb** [comment] 2022-10-27 17:02
And given that #2828 is closed, I'm going to close this one.

**Closed by atomb** 2022-10-27 17:02 UTC

**Comment by PrisionMike** [comment] 2022-10-28 12:16
I tried reading the marked issues, but I do not understand what exactly I should do to fix it?  Could you refer me to the actual process to fix it? In simple terms if possible.

**Comment by keyboardDrummer** [comment] 2022-10-28 12:22
The issue will be resolved once a new Dafny IDE is released which should happen soon. Until that, you can select "latest nightly" as the Dafny version in VSCode's Dafny settings.
