### ISSUE TITLE
Flaky test: DafnyTestGeneration

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#5549] opened 2024-06-10 18:59 UTC
```
[createdump] Gathering state for process 14902 dotnet
[createdump] Writing full dump to file /tmp/63376073-40fd-4da9-b362-f305505f5863/dotnet_14902_20240607T191257_hangdump.dmp
[createdump] Written 2369458176 bytes (578481 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written
The active test run was aborted. Reason: Test host process crashed
Data collector 'Blame' message: The specified inactivity time of 5 minutes has elapsed. Collecting hang dumps from testhost and its child processes.

Test Run Aborted.
Total tests: Unknown
     Passed: 66
 Total time: 5.9117 Minutes
Results File: /home/runner/work/dafny/dafny/dafny/Source/DafnyTestGeneration.Test/TestResults/_fv-az1423-926_[202](https://github.com/dafny-lang/dafny/actions/runs/9421832951/job/25956793854#step:14:203)4-06-07_19_07_41.trx

The active Test Run was aborted because the host process exited unexpectedly. Please inspect the call stack above, if available, to get more information about where the exception originated from.
The test running when the crash occurred: 
DafnyTestGeneration.Test.BasicTypes.CharsUnspecified

This test may, or may not be the source of the crash.

Attachments:
  /home/runner/work/dafny/dafny/dafny/Source/DafnyTestGeneration.Test/TestResults/57c50c19-a589-487a-8878-3a21be823416/coverage.cobertura.xml
  /home/runner/work/dafny/dafny/dafny/Source/DafnyTestGeneration.Test/TestResults/57c50c19-a589-487a-8878-3a21be823416/dotnet_14902_20240607T191257_hangdump.dmp
  /home/runner/work/dafny/dafny/dafny/Source/DafnyTestGeneration.Test/TestResults/57c50c19-a589-487a-8878-3a21be823416/Sequence_bfe1e78d842e48909d51e7ed48a7245f.xml
```

See this failng CI test run:
https://github.com/dafny-lang/dafny/actions/runs/9421832951/job/25956793854

**Comment by MikaelMayer** [comment] 2024-06-10 19:38
Another one of the same type https://github.com/dafny-lang/dafny/actions/runs/9454035921/job/26040724751?pr=5538

```
[createdump] Gathering state for process 21398 
[createdump] Writing full dump to file /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/e934896f-1a15-46b3-8932-3840bac55d61/dotnet_21398_20240610T193037_hangdump.dmp
[createdump] Written 3430629992 bytes (837556 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written
The active test run was aborted. Reason: Test host process crashed
Data collector 'Blame' message: The specified inactivity time of 5 minutes has elapsed. Collecting hang dumps from testhost and its child processes.

Test Run Aborted.
Total tests: Unknown
     Passed: 55
 Total time: 7.5913 Minutes
Results File: /Users/runner/work/dafny/dafny/dafny/Source/DafnyTestGeneration.Test/TestResults/_Mac-1718044072621_2024-06-10_19_24_43.trx

The active Test Run was aborted because the host process exited unexpectedly. Please inspect the call stack above, if available, to get more information about where the exception originated from.
The test running when the crash occurred: 
DafnyTestGeneration.Test.WarningTests.UnsupportedInputTypeClass
DafnyTestGeneration.Test.BasicTypes.Ints

This test may, or may not be the source of the crash.

Attachments:
  /Users/runner/work/dafny/dafny/dafny/Source/DafnyTestGeneration.Test/TestResults/7d8c79b6-8b77-493e-a5da-af6bce0e2ba5/coverage.cobertura.xml
  /Users/runner/work/dafny/dafny/dafny/Source/DafnyTestGeneration.Test/TestResults/7d8c79b6-8b77-493e-a5da-af6bce0e2ba5/dotnet_21398_20240610T193037_hangdump.dmp
  /Users/runner/work/dafny/dafny/dafny/Source/DafnyTestGeneration.Test/TestResults/7d8c79b6-8b77-493e-a5da-af6bce0e2ba5/Sequence_60c87eea3c3448f783bf0c3c3eff97b4.xml
```

**Comment by MikaelMayer** [comment] 2024-06-11 02:13
Another instance https://github.com/dafny-lang/dafny/actions/runs/9455927389/job/26046773236?pr=5440

```
[xUnit.net 00:01:12.01]     DafnyTestGeneration.Test.Various.PathBasedTests(optionSettings: [Action`1 { Method = Void <OptionSettings>b__5_0(Microsoft.Dafny.DafnyOptions), Target = <>c { ... } }]) [FAIL]
[xUnit.net 00:01:12.02]       System.Threading.Tasks.TaskCanceledException : A task was canceled.
[xUnit.net 00:01:12.02]       Stack Trace:
[xUnit.net 00:01:12.02]         /Users/runner/work/dafny/dafny/dafny/Source/DafnyTestGeneration.Test/Various.cs(227,0): at DafnyTestGeneration.Test.Various.PathBasedTests(List`1 optionSettings)
[xUnit.net 00:01:12.02]         --- End of stack trace from previous location ---
[xUnit.net 00:01:12.02]       Output:
[xUnit.net 00:01:12.02]         // Constructing the test for Paths.eightPaths path through /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(4,2):initialstate#2708446,2708447,2708448,2708449,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(10,4):initialstate#2708450,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(10,22)#thenBranch#2708451,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(10,38)#2708453,2708454,2708455,2708456,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(5,49)#2708457,2708458,2708459,2708460,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(10,4):initialstate#2708461,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(10,22)#thenBranch#2708462,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(10,38)#2708464,2708465,2708466,2708467...
[xUnit.net 00:01:12.02]         // Constructing the test for Paths.eightPaths path through /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(4,2):initialstate#2708446,2708447,2708448,2708449,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(10,4):initialstate#2708450,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(10,22)#thenBranch#2708451,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(10,38)#2708453,2708454,2708455,2708456,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(5,49)#2708457,2708458,2708459,2708460,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(10,4):initialstate#2708461,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(10,38)#elseBranch#2708463,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(10,38)#2708464,2708465,2708466,2708467...
[xUnit.net 00:01:12.02]         // Constructing the test for Paths.eightPaths path through /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(4,2):initialstate#2708446,2708447,2708448,2708449,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(10,4):initialstate#2708450,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(10,38)#elseBranch#2708452,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(10,38)#2708453,2708454,2708455,2708456,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(5,49)#2708457,2708458,2708459,2708460,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(10,4):initialstate#2708461,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(10,22)#thenBranch#2708462,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(10,38)#2708464,2708465,2708466,2708467...
  Failed DafnyTestGeneration.Test.Various.PathBasedTests(optionSettings: [Action`1 { Method = Void <OptionSettings>b__5_0(Microsoft.Dafny.DafnyOptions), Target = <>c { ... } }]) [50 s]
  Error Message:
   System.Threading.Tasks.TaskCanceledException : A task was canceled.
  Stack Trace:
     at DafnyTestGeneration.Test.Various.PathBasedTests(List`1 optionSettings) in /Users/runner/work/dafny/dafny/dafny/Source/DafnyTestGeneration.Test/Various.cs:line 227
--- End of stack trace from previous location ---
  Standard Output Messages:
 // Constructing the test for Paths.eightPaths path through /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(4,2):initialstate#2708446,2708447,2708448,2708449,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(10,4):initialstate#2708450,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(10,22)#thenBranch#2708451,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(10,38)#2708453,2708454,2708455,2708456,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(5,49)#2708457,2708458,2708459,2708460,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(10,4):initialstate#2708461,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(10,22)#thenBranch#2708462,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(10,38)#2708464,2708465,2708466,2708467...
 // Constructing the test for Paths.eightPaths path through /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(4,2):initialstate#2708446,2708447,2708448,2708449,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(10,4):initialstate#2708450,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(10,22)#thenBranch#2708451,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(10,38)#2708453,2708454,2708455,2708456,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(5,49)#2708457,2708458,2708459,2708460,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(10,4):initialstate#2708461,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(10,38)#elseBranch#2708463,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(10,38)#2708464,2708465,2708466,2708467...
 // Constructing the test for Paths.eightPaths path through /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(4,2):initialstate#2708446,2708447,2708448,2708449,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(10,4):initialstate#2708450,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(10,38)#elseBranch#2708452,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(10,38)#2708453,2708454,2708455,2708456,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(5,49)#2708457,2708458,2708459,2708460,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(10,4):initialstate#2708461,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(10,22)#thenBranch#2708462,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/parseUtils.dfy(10,38)#2708464,2708465,2708466,2708467...


```

**Comment by keyboardDrummer** [comment] 2024-06-11 08:13
Closing as duplicate of https://github.com/dafny-lang/dafny/issues/5488

**Closed by keyboardDrummer** 2024-06-11 08:13 UTC
Labels: kind: language development speed
