### ISSUE TITLE
Trait predicates stop working when in different files

### ISSUE THREAD

**Issue by jorge-jbs** [dafny-lang/dafny#989] opened 2020-12-22 18:54 UTC
Suppose we have this code:

```dafny
trait FooTrait {
  predicate Valid()
    reads this
}

class Foo extends FooTrait {
  var x: nat;

  predicate Valid()
    reads this
  {
    x % 2 == 0
  }

  constructor()
    ensures Valid()
  {
    x := 0;
  }
}

method main() {
  var x: Foo := new Foo();
  assert x.Valid();
  var y: FooTrait := x;
  assert x.Valid();
  assert y.Valid();
}
```

It works nicely. But if we move each definition to different files in the following way it no longer works (the last assertion fails):

`A.dfy`

```dafny
include "B.dfy"
include "C.dfy"

method main() {
  /* ... */
}
```

`B.dfy`

```dafny
trait FooTrait {
  /* ... */
}
```

`C.dfy`

```dafny
include "B.dfy"

class Foo extends FooTrait {
  /* ... */
}
```

Why is there different behavior depending on whether we have everything in the same file or in different ones? Is this a bug?

BTW, if we merge `A.dfy` and `C.dfy` it works again.

**Comment by davidcok** [comment] 2020-12-24 20:39
HI - what version and platform are you using? and you are using Z3 4.8.4? 
This currently causes no problems for me with current master on a Mac.
We did correct a problem recently in which include file names were all converted to lowercase, but here it seems all files are found.

**Comment by jorge-jbs** [comment] 2020-12-25 10:14
I'm using Dafny 2.3.0.10506 and Z3 4.8.5. I'm on Linux (NixOS).

Here is what I get when I run `dafny A.dfy`, maybe it helps:

```
Dafny 2.3.0.10506
Prover error: line 18 column 28: unknown parameter 'model_compress'
Legal parameters are:
  auto_config (bool) (default: true)
  debug_ref_count (bool) (default: false)
  dot_proof_file (string) (default: proof.dot)
  dump_models (bool) (default: false)
  memory_high_watermark (unsigned int) (default: 0)
  memory_max_alloc_count (unsigned int) (default: 0)
  memory_max_size (unsigned int) (default: 0)
  model (bool) (default: true)
  model_validate (bool) (default: false)
  proof (bool) (default: false)
  rlimit (unsigned int) (default: 0)
  smtlib2_compliant (bool) (default: false)
  stats (bool) (default: false)
  timeout (unsigned int) (default: 4294967295)
  trace (bool) (default: false)
  trace_file_name (string) (default: z3.log)
  type_check (bool) (default: true)
  unsat_core (bool) (default: false)
  verbose (unsigned int) (default: 0)
  warning (bool) (default: true)
  well_sorted_check (bool) (default: false)
A.dfy(9,16): Error: assertion violation
Execution trace:
    (0,0): anon0

Dafny program verifier finished with 0 verified, 1 error
```

**Comment by RustanLeino** [comment] 2020-12-28 20:23
This problem is due to a change in option names that started in Z3 version 4.8.5. Switch to Z3 v.4.8.4 and then I expect this problem to go away. (I don't understand why the problem did not show up when you used just one file.)

**Comment by RustanLeino** [comment] 2020-12-30 22:25
Thanks for the bug report. I was able to reproduce it using Dafny 2.3.0. This bug has been fixed in the current version of Dafny (version 3.0.0 pre-release ...).

**Closed by RustanLeino** 2020-12-30 22:25 UTC
