### ISSUE TITLE
Able to ensure false without assumptions

### ISSUE THREAD

**Issue by JonathanStarup** [dafny-lang/dafny#415] opened 2019-11-06 23:21 UTC
We are two students who are using Dafny for the first time and was trying to prove union-find when we ran into weird behavior. Dafny verified some very odd asserts and we could even assert false. We removed as much as possible from the code, but we can in this program, ensure false in main without any `requires` or `assume`. We wouldn't think this could happen no matter what code we wrote outside of main but couldn't find any errors either.

```
class Main {
  method main()
  ensures false;
  {
    var n := new Node;
    n.parent := 0;
    n.lengthToRoot := 0;
    n.root := 0;
    var G := new Node[1](_ => n);
    unite(G, 0, 0);
  }

  predicate graph(G: array<Node>)
    reads G, set i: nat | i < G.Length :: G[i]
  { (forall i: nat :: i < G.Length ==> (
      (G[i].parent < G.Length) &&
      (G[i].lengthToRoot == 0 <==> G[i].parent == i) &&
      (G[i].lengthToRoot > 0 ==> G[G[i].parent].lengthToRoot < G[i].lengthToRoot) &&
      (G[i].lengthToRoot == 0 <==> G[i].root == i) &&
      (G[i].root == G[G[i].parent].root)
    )) &&
    forall i: nat, j: nat :: i < j < G.Length ==> G[i] != G[j]
  }

  method Find(G: array<Node>, a: nat) returns (res: nat)
    requires a < G.Length
    requires graph(G)
    ensures graph(G)

    modifies G, set i: nat | i < G.Length :: G[i]
    decreases G[a].lengthToRoot

    ensures res == G[a].root

    ensures res < G.Length
    ensures G[res].lengthToRoot == 0
    ensures G[res].parent == res
    ensures forall i: nat :: i < G.Length ==> old(G[i].lengthToRoot) == G[i].lengthToRoot
    ensures forall i: nat :: i < G.Length ==> old(G[i]) == G[i]
    ensures forall i: nat :: i < G.Length ==> old(G[i].root) == G[i].root
  {
    if G[a].parent != a {
      G[a].parent := Find(G, G[a].parent);
    }
    return G[a].parent;
  }

  method unite(G: array<Node>, a: nat, b: nat) 
    requires a < G.Length
    requires b < G.Length
    requires graph(G)
    ensures G[a].root == G[b].root;
    ensures G[a].root != G[b].root;
    modifies G, set i: nat | i < G.Length :: G[i]
  {
    var rootA := Find(G, a);
    var rootB := Find(G, b);
  }
}

class Node {
  var parent: nat;
  ghost var lengthToRoot: nat;
  ghost var root: nat;
}
```

**Comment by mschlaipfer** [comment] 2019-11-07 15:50
Dafny should complain about your unsatisfiable post-condition of `unite`, but doesn't.
```
ensures G[a].root == G[b].root;
ensures G[a].root != G[b].root;
```
This false post-condition then propagates to `main`. Maybe this helps you fix your program.

BTW: you don't need to end `ensures` annotations with semi-colons

**Comment by RustanLeino** [comment] 2019-11-07 17:31
I'm unable to reproduce the problem with `unite`, because it times out or runs out of memory after 30 minutes. Is that the behavior you're seeing as well, or does the verifier actually claim to verify `unite`?

**Comment by mschlaipfer** [comment] 2019-11-07 17:56
I get a timeout on the command line, but in VSCode it somehow "verifies". Could be an IDE issue as well, but I can reproduce it there.

**Comment by JonathanStarup** [comment] 2019-11-07 21:50
We run Dafny through the VSCode extension and have not tried to run it directly. It didn't occur to us that it could be an issue with the IDE. We also observed that the program would time out inconsistently in some variations of the above program. It might be a problem in how the extension handles timeouts I guess, but we will continue the project running Dafny directly.

**Comment by RustanLeino** [comment] 2020-01-04 01:37
Is there any progress on this? Can you reproduce it or should I close the issue?

**Comment by robin-aws** [comment] 2020-02-12 00:21
I was able to produce the spurious verification in VSCode. The toolbar at the bottom goes from "Verifying" to "Idle" on this file, taking about 10-15 seconds, and only gives a couple of undecipherable warnings (copy and pasted below):

```
{
	"resource": "/Users/salkeldr/Documents/GitHub/dafny/Test/git-issues/git-issue-415.dfy",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 2,
	"message": "For expression \"(i < G.Length ==> G[i].parent < G.Length) && (i < G.Length ==> (G[i].lengthToRoot == 0 <==> G[i].parent == i)) && (i < G.Length ==> (G[i].lengthToRoot == 0 <==> G[i].root == i))\":",
	"source": "Dafny VSCode",
	"startLineNumber": 15,
	"startColumn": 5,
	"endLineNumber": 15,
	"endColumn": 1.7976931348623157e+308
}

{
	"resource": "/Users/salkeldr/Documents/GitHub/dafny/Test/git-issues/git-issue-415.dfy",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 2,
	"message": "For expression \"(i < G.Length ==> G[i].lengthToRoot > 0 ==> G[G[i].parent].lengthToRoot < G[i].lengthToRoot) && (i < G.Length ==> G[i].root == G[G[i].parent].root)\":",
	"source": "Dafny VSCode",
	"startLineNumber": 15,
	"startColumn": 5,
	"endLineNumber": 15,
	"endColumn": 1.7976931348623157e+308
}
```

**Comment by robin-aws** [comment] 2021-09-28 18:33
I'm not able to reproduce this behavior with the latest IDE plugin and language server, and it looks extremely likely that https://github.com/dafny-lang/dafny/pull/1430 fixed the issue. We also have https://github.com/DafnyVSCode/Dafny-VSCode/issues/64 on the legacy version, so we can track whether it's worth backporting the fix.

Given that I'm going to go ahead and close this, but please feel free to reopen if needed!

**Closed by robin-aws** 2021-09-28 18:33 UTC
Labels: bug, soundness
