### ISSUE TITLE
Flaky test Microsoft.Dafny.LanguageServer.IntegrationTest.Synchronization.ProjectManagerDatabaseTest.ChangeAndUndoProjectWithMultipleFile

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#5550] opened 2024-06-10 21:41 UTC
Happened here:

https://github.com/dafny-lang/dafny/actions/runs/9453995964/job/26040585001?pr=5440
```
[xUnit.net 00:00:58.71]     Microsoft.Dafny.LanguageServer.IntegrationTest.Synchronization.ProjectManagerDatabaseTest.ChangeAndUndoProjectWithMultipleFiles [FAIL]
[xUnit.net 00:00:58.71]       Assert.NotEmpty() Failure
[xUnit.net 00:00:58.71]       Stack Trace:
[xUnit.net 00:00:58.71]         D:\a\dafny\dafny\dafny\Source\DafnyLanguageServer.Test\Synchronization\ProjectManagerDatabaseTest.cs(45,0): at Microsoft.Dafny.LanguageServer.IntegrationTest.Synchronization.ProjectManagerDatabaseTest.ChangeAndUndoProjectWithMultipleFiles()
[xUnit.net 00:00:58.71]         --- End of stack trace from previous location ---
fail: Microsoft.Dafny.Compilation[0]
      Caught error in statusUpdates observable.
      System.Exception: CheckerPool was already disposed
         at VC.CheckerPool.FindCheckerFor(Program program, Split split, CancellationToken cancellationToken)
         at Microsoft.Boogie.VerificationTask.StartRun(CancellationToken cancellationToken)+MoveNext()
         at Microsoft.Boogie.VerificationTask.StartRun(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
         at System.Linq.AsyncEnumerable.ToObservableObservable`1.<>c__DisplayClass2_0.<<Subscribe>g__Core|0>d.MoveNext() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToObservable.cs:line 50
  Failed Microsoft.Dafny.LanguageServer.IntegrationTest.Synchronization.ProjectManagerDatabaseTest.ChangeAndUndoProjectWithMultipleFiles [137 ms]
```

**Comment by keyboardDrummer** [comment] 2024-06-10 21:45
Duplicate of https://github.com/dafny-lang/dafny/issues/5510

**Closed by keyboardDrummer** 2024-06-10 21:45 UTC
Labels: kind: language development speed
