### ISSUE TITLE
Dafny 4.0 suggestion: Remove the `-compile` and `-spillTargetCode` option

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#2351] opened 2022-07-01 18:25 UTC
I have a hard time remembering the numeric option for `-compile` or `/compile` and `-spillTargetCode`. Since what we want to do with a file is so fundamental, I think it would make more sense to put command names there such as these ones:

| old command | New suggested command |
|-----------------|-----------------|
| `dafny -compile:0 f.dfy` | `dafny verify f.dfy` |
| `dafny -compile:0 -spillTargetCode:2 -compileTarget:cs f.dfy` | `dafny translate -lang:cs f.dfy` |
| `dafny -compile:1 f.dfy` | `dafny compile f.dfy` |
| `dafny -compile:1 -spillTargetCode:1 f.dfy` | `dafny translate compile f.dfy` |
| `dafny -compile:2 f.dfy` | `dafny compile --force f.dfy` |
| `dafny -compile:3 f.dfy` | `dafny run f.dfy` |
| `dafny -compile:4 f.dfy` | `dafny run --force f.dfy` |

Note that the long "-compileTarget" should be replaced by "lang" because, in the case of cs, we could as well compile to dotnet by going through F#.

I'm still wondering what the default option should be if we invoke `dafny f.dfy`. The current setting states it will be `dafny compile f.dfy`, which I think is ok.

That way, we will later be able to add other commands, such as `dafny format`, etc.

**Comment by cpitclaudel** [comment] 2022-07-01 19:26
We might want to separate `dafny compile` from `dafny codegen` (aka `/spillTargetCode`), too?

**Comment by robin-aws** [comment] 2022-07-01 19:33
+1, and in fact we've come to the same conclusion earlier: https://github.com/dafny-lang/dafny/issues/2036 :)

Even better though, notice that this wouldn't be a breaking change (copied from here: https://github.com/dafny-lang/dafny/issues/1322):

"We wouldn't even be breaking backwards compatibility, since non-flag arguments are currently rejected if they don't have a recognized extension for "other files" for the given compilation target."

**Comment by MikaelMayer** [comment] 2022-07-01 20:04
Oh I was away when you wrote that, glad we are almost on the same page !
I'm in favor or not breaking backward compatibility too, but I would like at least all relevant combinations of /spitllTargetCode and /compile be available through simple commands.

Also, the use of `-force` or `--force` so that I don't need to remember which one of 0, 1, 2, 3, 4 forces.

**Comment by RustanLeino** [comment] 2022-07-02 00:07
I prefer `verify` to `check`. Everything else looks good. (In the future, I would also like a `typecheck` option that would just resolve and type check the program, but not proceed to verification and compilation.)

**Comment by robin-aws** [comment] 2022-08-12 21:55
Closing this as a duplicate of #2036, which has much more recent discussion.

**Closed by robin-aws** 2022-08-12 21:55 UTC
Labels: part: tools, breaking-change, kind: language proposals
