### ISSUE TITLE
dafny CLI installed from NuGet never completes

### ISSUE THREAD

**Issue by seebees** [dafny-lang/dafny#2561] opened 2022-08-06 04:21 UTC
Using the latest version of dafny from NuGet the well-formedness checks pass,
but then the command line hangs.

However verifying the same using Dafny: Compile in the IDE (with the same version) works.

**Comment by MikaelMayer** [comment] 2022-08-08 14:04
Can you please post a small repro?

**Comment by atomb** [comment] 2022-09-12 16:55
I believe that this is an instance of #2370, and can be resolved by installing [Z3 4.8.5](https://github.com/Z3Prover/z3/releases/tag/Z3-4.8.5) and putting it in the path. Dafny should really be providing a more useful error message here.

**Comment by robin-aws** [comment] 2022-09-23 17:55
Closing as dupe of #2370

**Closed by robin-aws** 2022-09-23 17:55 UTC
Labels: status: needs-info, part: tools
