### ISSUE TITLE
Parity between `dafny` and `dafny translate` in CLI

### ISSUE THREAD

**Issue by lucasmcdonald3** [dafny-lang/dafny#4888] opened 2023-12-15 00:10 UTC
### Summary

The sets of supported compile flags for `dafny` and `dafny translate` are different.
This is an issue if I want to combine `outer-module` and `runAllTests`.
`dafny translate` supports `outer-module`, but not `runAllTests` (nor something like `--run-all-tests`).
`dafny` supports `runAllTests`, but not `outer-module` (nor something like `-outerModule`).

Fixing this will allow Smithy-Dafny to generate tests for code that requires the `--outer-module` flag.

This is currently low-priority; I'm not sure if Smithy-Dafny will end up using `outer-module`, so I may not end up using these flags together. I just want to cut this for tracking.

### Background and Motivation

Using `outer-module` in conjunction with `runAllTests` is not possible. I encountered this when trying to build tests for a project that would use `outer-module`.

### Proposed Feature

Either/or are supported:

`dafny ... -outerModule:path.to.module`

or

`dafny translate [lang] ... --run-all-tests:1`

**Comment by keyboardDrummer** [comment] 2023-12-15 12:07
Duplicate of https://github.com/dafny-lang/dafny/issues/3818

**Closed** 2023-12-20 10:41 UTC
Labels: kind: enhancement
