### ISSUE TITLE
Map comprehension with assignment can produce ugly Boogie errors

### ISSUE THREAD

**Issue by jonhnet** [dafny-lang/dafny#468] opened 2019-12-27 22:54 UTC
Map comprehensions have a ":=" syntax that should allow me to construct a map by ranging over one set and having the keys of the map be a function of that set, rather than members of the set itself. I've gotten it to work in one case (although I haven't made an isolated example). However, in another simple case, it breaks with an internal translation error. The small example:
```
lemma foo() {
  var seqa := ["a", "b", "c"];
  var seqb := ["x", "y", "z"];
  var x := map i | i in {0,1,2} :: seqa[i] := seqb[i];
}
```
The error:

> $ dafny /compile:0 test.dfy
> Dafny 2.3.0.10506
> (0,-1): Error: invalid argument types (int and Seq Box) to binary operator ==
> test.dfy(4,11): Error: invalid type for argument 0 in application of map$project$0#0#i#0: int (expected: Seq Box)
> 2 type checking errors detected in /tmp/test__module.bpl
> 
> *** Encountered internal translation error - re-running Boogie to get better debug information
> 
> /tmp/test__module.bpl(2737,34): Error: invalid argument types (int and Seq Box) to binary operator ==
> /tmp/test__module.bpl(2738,77): Error: invalid type for argument 0 in application of map$project$0#0#i#0: int (expected: Seq Box)
> 2 type checking errors detected in /tmp/test__module.bpl
>

**Comment by RustanLeino** [comment] 2020-01-03 00:59
Duplicate of https://github.com/dafny-lang/dafny/issues/315, which was fixed in changeset 7e0f2e39.

(Even when this construct is translated correctly, it can be hard to work with. If there are important or often occurring test cases that you find to be hard or impossible to deal with, please report those.)

**Closed by RustanLeino** 2020-01-03 00:59 UTC
