### ISSUE TITLE
Standard Library

### ISSUE THREAD

**Issue by nicekingwei** [dafny-lang/dafny#117] opened 2017-05-30 03:26 UTC
I'm deeply impressed by Dafny and I believe it's the most beautiful language I have ever used.I want to use it in my projects and promote it to my friends.But the work is difficult without any libraries.Would you like to develop some libraries?Or you can just list the functions of libraries,and maybe I can help to complete it.Thanks for your work of developing Dafny,it's awesome and meaningful!

**Comment by robin-aws** [comment] 2020-02-11 21:49
Closing as a duplicate of #482 - this one was here first and has a lovely sentiment, but there's more content on the newer one so hopefully @nicekingwei won't mind. :)

**Closed by robin-aws** 2020-02-11 21:49 UTC
Labels: enhancement
