### ISSUE TITLE
Resolver invariant violated while checking iterator

### ISSUE THREAD

**Issue by ssomayyajula** [dafny-lang/dafny#5354] opened 2024-04-23 23:18 UTC
### Dafny version

4.6.0

### Code to produce this issue

```dafny
class Account { var balance: nat }

iterator Deposit(self: Account, amount: nat)
  ensures self.balance == old(self.balance) + amount
{
  self.balance := self.balance + amount;
}
```

### What happened?

For the (only) `e` in `Ensures` in `Source/DafnyCore/AST/TypeDeclarations/IteratorDecl` post-resolution, e.g., in `CreateIteratorMethodSpecs()` --- despite `e.WasResolved()` holding, the `BinaryOpExpr` corresponding to `old(self.balance) + amount` has its `ResolvedOpcode` field set to `YetUndetermined` (it should be `ResolvedOpcode.Add`).

### What type of operating system are you experiencing the problem on?

Mac

**Comment by keyboardDrummer** [comment] 2024-04-24 09:30
I don't understand this bug report. It does not seem to report a user facing bug, but rather a problem faced when working on the Dafny language itself. I would argue that unless the problem has user visible consequences, it's not a bug. Closing but please reopen if I misunderstand.

**Closed by keyboardDrummer** 2024-04-24 09:30 UTC
Labels: kind: bug
