### ISSUE TITLE
Dafny Verifying forever in VSCode: Urgent help needed for teaching in class

### ISSUE THREAD

**Issue by AzadehFarzan** [dafny-lang/dafny#1426] opened 2021-09-10 14:36 UTC
I have seen the other thread about this and the solution does not seem to work. The problem seems to be new (with the language server?) since it happens on the files that in the past did not have the same problem. 

To be exact, this is for cases that I do not expect verification to be completed. I expect to get a message that certain postconditions do not hold on certain paths and therefore more (proof) effort is needed.

To make everything worse, there is no way of gracefully stopping this, and you cannot edit the file further and restart the verification process. I have to kill the background Z3 process manually. 

I remember in the past, the "/timeLimit:n" option as a language server argument would work in curbing the time spent in Z3.  Now, it does not seem to have any effect anymore. The strange thing is that the same option works fine as a compiler argument, but that is useless for live (in VSCode) verification.

I will appreciate it if someone can get in touch and resolve this issue. We use this for teaching in an undergraduate course and it has been fine for years now, and somehow this year, everything broke down. 

I am on MacOS. 

Is there any source for a full list of language server options (to be used in the settings)?

**Comment by YellPika** [comment] 2021-09-10 20:52
To follow up, here is the code we are having trouble with:

```dafny
predicate even(a: nat) {
    exists k: nat :: a == 2 * k
}

lemma EvenSquare(n: nat)
    requires even(n * n);
    ensures even(n);
{
}

lemma SquareRoot2NotRational(p: nat, q: nat)
    requires p > 0 && q > 0
    ensures p * p !=  2 * q * q
{
    if (p * p) ==  2 * (q * q) {
        calc == {
            (2 * q - p) * (2 * q - p);
            4 * q * q + p * p - 4 * p * q;
            {assert 2 * q * q == p * p;}
            2 * q * q + 2 * p * p - 4 * p * q;
            2 * (p - q) * (p - q);
        }
        SquareRoot2NotRational(2 * q - p, p - q);
    }
}
```

We get inconsistent results depending on whether we comment various things out, impose timeouts, or run from the command line vs. check in VSCode.

1. As is, this code causes the Dafny language server to get into an infinite loop somewhere. There is no way to stop the server aside from killing the process. The "Restart DafnyServer" command (F9) does not seem to work.
2. If we add {:timeLimit 1} to `EvenSquare`, Dafny rejects the program _when run from the command line only._ Inside VSCode, the Dafny extension claims the code is successfully verified.
3. If `SquareRoot2NotRational` is commented out, `EvenSquare` is rejected both in VSCode and on the command line.
4. If `EvenSquare` is commented out, `SquareRoot2NotRational` is accepted both in VSCode and on the command line.

I am running Arch Linux, so the problem is likely not platform specific (i.e. unrelated to #1213).

**Comment by RustanLeino** [comment] 2021-09-10 21:55
Thank you for the bug report and the additional example. We'd like to hammer out these problems with the verifier and IDE, and are looking into it. In this particular example, I'm guess the non-linear arithmetic (that is, multiplication of two variables) that's causing the extreme slow-down in the first place. But we'd still want the IDE to remain responsive.

@camrein Any thoughts on this one?

**Comment by AzadehFarzan** [comment] 2021-09-10 22:05
Rustan,

It is not the non-linear arithmetic thing. I used the same example in my
class last year without a problem. It would just "not verify" without the
call to the induction hypothesis; it would not go into a forever loop with
the IDE.

We had to resort to telling the students to use timelimits to curb the
issue. But then, with the limits, the IDE mistakenly tells the user that
the lemma is verified. Using Dafny at the commandline would produce the
correct response of "timeout". This makes the IDE entirely unusable for
students, which is a big deal. We mainly reached out because the bug seems
to be new (as in it was not there before).

I am attaching a shorter version of this problem with appropriate comments.
The class on the Dafny topic is ongoing. If you could fix this issue for us
in a few days, it will save it. Otherwise, a whole year worth of students
will get the wrong impression of Dafny :-)

**Comment by AzadehFarzan** [comment] 2021-09-12 18:00
OK, I tried but I couldn't make it work with the patch. The server keeps
crashing and never comes up. Is this for MacOSX? I am asking because two of
the files in this patch do not exist in my version of the directory you
mentioned. So, I have 5 out of 7 only.

What next? :-)

**Comment by camrein** [comment] 2021-09-12 18:45
That's interesting that this build is not working on OSX. Manually starting the server from the terminal using `dotnet DafnyLanguageServer.dll` leads to a missing dll (System.Runtime.Caching.dll). I've packed the whole language server distribution including all 3rd party dlls. At least on my OSX test device that fixed the issue.
[LanguageServer.v3.2.0.patched-full.zip](https://github.com/dafny-lang/dafny/files/7150130/LanguageServer.v3.2.0.patched-full.zip)

**Comment by AzadehFarzan** [comment] 2021-09-13 16:43
It seems like just copying DafnyLanguageServer.dll  from this last batch
alone does the trick. Added bonus is that, in the new version, a request
for a redo with a fix now seems to stop the bad (forever) process and gets
one through. So, it is infinitely more functional than before now.

Meanwhile, your suggestion about reverting back to Dafny 2 was excellent as
well. All the old examples seem to work fine there, so far.

Thank you very much for the very quick responses to this. We can
communicate both solutions to the students, and hopefully, we will have
something functioning for them to get us through the course for now.

**Comment by camrein** [comment] 2021-09-14 06:41
Thank you for the confirmation. I'm glad that we could provide a good solution for you and your students.

If you're missing any specific features of Dafny 2 in Dafny 3, please open another issue. We left the option for Dafny 2 in the marketplace for problematic cases such as the one you had. But ultimately, we'd like people to have a smooth transition to Dafny 3.

As the necessary changes are now merged into the master branch, I close this issue for now.

**Closed by camrein** 2021-09-14 06:41 UTC
