### ISSUE TITLE
Add lint check on the argument of old()

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#2549] opened 2022-08-04 19:08 UTC
The example below was sent to us offline.
It suggests a lint check that warned if the argument of old() is a formal argument or anything else that is obviously not in the modifies clause (obvious == does not need a prover invocation)

```
class A {
  var s: set<string>
}

method foo(x: A)
  modifies x
{
  var init := x.s;
  x.s := x.s + {"a"};
  assert init == old(x).s;  // SHOULD BE old(x.s)
}
```

**Comment by cpitclaudel** [comment] 2022-08-04 22:46
Great idea! Though to be more precise, the problem isn't being in the modifies clause or being a formal, it's being an expression that doesn't refer to the heap :)

**Comment by keyboardDrummer** [comment] 2022-08-10 11:20
Duplicate of https://github.com/dafny-lang/dafny/issues/1989

**Closed by keyboardDrummer** 2022-08-10 11:20 UTC
Labels: area: error-reporting
