### ISSUE TITLE
 Doesn't recognize sequence with a subtype constraint as a sequence

### ISSUE THREAD

**Issue by txiang61** [dafny-lang/dafny#1157] opened 2021-03-26 19:41 UTC
``` 
type subString = x: seq<char> | 0 <= |x| < 0x8000_0000
function method foo(s: subString): subString { "0" }
method goo(s: subString) returns (eq: bool)
{
  if s != [] {
    ghost var s' := foo(s[0..]);
    assert s'[1..] == [];
  }
  return true;
}
```
I get the error `Error: multi-selection of elements requires a sequence or array (got subString)` for line
```
assert s'[1..] == [];
```

**Comment by tchajed** [comment] 2021-03-26 21:03
I believe this is a duplicate of #1113.

**Closed** 2021-03-26 21:44 UTC
