### ISSUE TITLE
Standard library for Dafny

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#482] opened 2020-01-09 03:31 UTC
As Dafny adds compilers and clients write Dafny code with the intention of producing output C#, Java, whatever, having a standard library will become critical. In addition any successful programming language needs one.

One particular need is standard names for types that translate into pre-defined types in the target languages (e.g., int32), so clients can rely on those types being appropriately translated.

I'm sure there will be heated debate about what should and should not be in such a library, names for things etc. ...

**Comment by robin-aws** [comment] 2020-01-09 19:48
Big +1 to this - @acioc is looking at getting a proper standard library off the ground. 

I'm also focussing on being able to build, release, and otherwise manage shared Dafny packages, addressing issues like #466 that are blocking this kind of modularization.

**Comment by parno** [comment] 2020-01-21 04:09
Yes, an extensible standard library would be a great addition.  As a sampling of the kinds of code/lemmas I'd like to see included (and perhaps as a starting point for such a library), we have a fair bit of code from our Ironclad and IronFleet projects (https://github.com/Microsoft/Ironclad), as well as our Vale work (https://github.com/project-everest/vale/tree/legacy_dafny/src).  Much of it is around reasoning about bits, bytes, words, and sequences thereof.

**Comment by robin-aws** [comment] 2021-09-22 21:18
Closing as a duplicate of #1236 (which has a lot more active discussion and worth leaving open for a while longer even though we have substantial code in https://github.com/dafny-lang/libraries now)

**Closed by robin-aws** 2021-09-22 21:18 UTC
Labels: enhancement
