### ISSUE TITLE
[Bug]: ThrowAddingDuplicateWithKeyException thrown in ReportAssertionBatchResult

### ISSUE THREAD

**Issue by dijkstracula** [dafny-lang/dafny#3105] opened 2022-11-23 23:47 UTC
### Dafny version

Dafny 3.9.1.41027

### Code to produce this issue

```dafny
https://github.com/dijkstracula/smrt/commit/97da7a16d961320c5daffc4d667090ce86d2cd53
```

### Command to run and results

```code
Loading the above project at the above commit in VS Code results in an LSP exception being thrown.
```

### What happened?

Verification sits at "Verified 5/7, verifying RefinesReadStep, RefinesWriteStep, ..." for about 10-15 seconds.  After waiting, then the crash happens.

At the exception point, the stack is:

```
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: assert Seq#Equal(BlockDisk.__default.Read(CowZonedDiskRefinesBlockDisk.__default.IC(c#0), CowZonedDiskRefinesBlockDisk.__default.I(c#0, s#0), block_id#0), val#0);

   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at VC.VCResult.ComputePerAssertOutcomes(Dictionary`2& perAssertOutcome, Dictionary`2& perAssertCounterExamples)
   at Microsoft.Dafny.LanguageServer.Workspace.VerificationProgressReporter.ReportAssertionBatchResult(AssertionBatchResult batchResult) in /Users/ntaylor/code/dafny/Source/DafnyLanguageServer/Workspace/VerificationProgressReporter.cs:line 298
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 54
   at System.Reactive.ObserveOnObserverNew`1.DrainStep(ConcurrentQueue`1 q) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 577
   at System.Reactive.ObserveOnObserverNew`1.DrainShortRunning(IScheduler recursiveScheduler) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 513
   at System.Reactive.Concurrency.EventLoopScheduler.Run() in /_/Rx.NET/Source/src/System.Reactive/Concurrency/EventLoopScheduler.cs:line 356
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Thread.StartCallback()
```

The problematic postcondition indicated in the exception is [https://github.com/dijkstracula/smrt/blob/97da7a16d961320c5daffc4d667090ce86d2cd53/src/Refinements/CowZonedDiskRefinesBlockDisk.dfy#L71](this one) - I haven't been able to diagnose a smaller repro test, apologies.  

### What type of Operating System are you seeing the problem on?

Mac

**Comment by robin-aws** [comment] 2022-11-24 22:25
I strongly suspect this is a dupe of https://github.com/dafny-lang/dafny/issues/2951, as the stack trace looks the same and I wasn't able to reproduce it with the tip of master. 

You can verify it's fixed if you select "latest nightly" as your `Dafny: Preferred Version` setting in the VS Code extension.

**Comment by dijkstracula** [comment] 2022-11-24 22:39
Thanks, Robin!  I should have made mention of that other issue: I agree that the stack trace looks basically the same, but I'm not using a binary release of Dafny but instead building from source; my current HEAD is 

```
➜  dafny git:(master) git log --oneline | head -n 1
3b6c8765 Ensure non-parseable SeqIndexs do not throw on parse failure (#3093)
➜  dafny git:(master)
```

Just to ensure that the VS Code extension isn't somehow also using a release version, I changed my Preferred Version from `latest` to `latest nightly` (which should be a no-op, since I'm specifying the path to Dafny and the Language Server manually) and, indeed, the crash still happened. 

One thing I should have mentioned: verification takes ~10-15 seconds before the crash actually happens on my end.  Initially only one error, relating to the postcondition in `CowZonedDiskRefinesBlockDisk::RefinesStep`, appears; after some time, then the crash happens. 

In general, sorry for the vague bug report - I was trying to get it out before US Thanksgiving started and cut corners in the process.  I'll update the report with better information now.

**Comment by MikaelMayer** [comment] 2022-11-25 17:07
Note: We need to bump Boogie's version. It's still not fixed in Dafny yet.

**Comment by dijkstracula** [comment] 2022-11-25 17:20
Is it the case that a new Boogie release also needs to be cut and pushed out?  The [Boogle.ExecutionEngine NuGet page](https://www.nuget.org/packages/Boogie.ExecutionEngine/#versions-body-tab) currently lists 2.15.9 as the most recent version, which matches the dependency version I'm seeing in DafnyPipeline.csproj too.

**Comment by MikaelMayer** [comment] 2022-11-25 17:22
Yes we need a new release of Boogie as well. The bug was fixed on November 1st, but the last release dates from October 25.

**Closed** 2022-11-30 22:49 UTC
Labels: part: language server, severity: crash
