### ISSUE TITLE
Inner extern modules with same name give a compilation error

### ISSUE THREAD

**Issue by codyroux** [dafny-lang/dafny#1966] opened 2022-04-04 19:24 UTC
The following code:

```
module foo {
  module {:extern} util {
    class C {}
  }
}

module bar {
  module {:extern} util {
    class D {}
  }
}
```

Compiled with the following command:
```
dafny /compile:0 my_file.dfy
```
gives the error
> `my_fild.dfy(8,19): Error: Modules 'util' and 'util' both have CompileName 'util_Compile'.
1 resolution/type errors detected in foo.dfy`

The issue is not present without the `{:extern}` pragma.

A possible workaround is `{:extern "foo.util"}` (resp `{:extern "bar.util"}`). Still I wonder if this restriction might be lifted.

Dafny version: `Dafny 3.4.0.40208`.

**Comment by txiang61** [comment] 2022-04-08 19:08
This is a duplicate of #1170

**Closed** 2022-04-09 00:16 UTC
