### ISSUE TITLE
[Bug]: Documentation: Type setting bug in Guide

### ISSUE THREAD

**Issue by RustanLeino** [dafny-lang/dafny#3132] opened 2022-11-29 18:38 UTC
### Dafny version

3.9.1

### Code to produce this issue

As reported by a user:  The online version of "Getting Started with Dafny: A Guide" :

https://dafny.org/latest/OnlineTutorial/guide

has a typesetting error near:

    {.editonly} method MultipleReturns(x: int, y: int)

And

    dafny {.edit} method Abs(x: int) returns (y: int) { if x < 0 { return -x; } else { return x; } }
    ```


### Command to run and results

See https://dafny.org/latest/OnlineTutorial/guide and search for \`\`\`

### What happened?

See the page

### What type of Operating System are you seeing the problem on?

Mac

**Comment by davidcok** [comment] 2022-11-29 19:15
Closing as a duplicate of #3110 and subsumed in #2676

**Closed by davidcok** 2022-11-29 19:15 UTC
Labels: part: documentation
