### ISSUE TITLE
Parallel assignment occurs sequentially #bug

### ISSUE THREAD

**Issue by drorkliger** [dafny-lang/dafny#506] opened 2020-01-15 19:25 UTC
Dafny assigns sequentially instead of what supposed to be a parallel assignment.

This is an example of a code that runs just fine with no RunTimeErrors.
https://www.riseforfun.com/Dafny/mieKE

And this is the same code with a change in the order of assignment in line 117. **This code has an RTE.**
https://www.riseforfun.com/Dafny/uaMz

**Comment by RustanLeino** [comment] 2020-01-16 02:23
That's a compiler bug. Thanks for reporting.

**Comment by davidcok** [comment] 2020-06-01 14:12
I am attempting to reproduce and resolve this bug -- however, the links given in the report above do not, for me, lead to any code snippets. Can you (drorkliger) fix that or paste the code directly?

**Comment by drorkliger** [comment] 2020-06-01 14:33
Sure, the code below works, switching the assignment order in the relevant line makes it fail. 
(I marked the relevant line in the code).

method Main()
{
	var a := new int[8];
	a[0],a[1],a[2],a[3],a[4],a[5],a[6],a[7] := 7,2,1,5,8,4,0,3;
	print "Original contents of the array:                 ";
	print a[..];
	LeftRotate(a, 2);
	print "\nContents of the array after left-rotation by 2: ";
	print a[..];
}

method {:verify false} LeftRotate'(a: array<int>, n: nat) // the algorithm
	requires a.Length != 0
	ensures forall i :: 0 <= i < a.Length ==> a[i] == old(a[(i+n)%a.Length])
	modifies a
{
	var index, q := 0, a[..];
	while index < a.Length
		invariant Inv(a[..],q,n,index)
		decreases a.Length - index
			{
				a[index], index := q[(index+n)%|q|],index+1;
			}
}

method LeftRotate(a: array<int>, n: nat)
	requires a.Length != 0
	ensures forall i :: 0 <= i < a.Length ==> a[i] == old(a[(i+n)%a.Length])
	modifies a
	{
		// introduce local variable
		var q: seq<int>, index: nat;
		index,q := LeftRotate1(a,n);
	}
method LeftRotate1(a: array<int>, n: nat) returns (index: nat, q: seq<int>)
	requires a.Length != 0
	ensures forall i :: 0 <= i < a.Length ==> a[i] == old(a[(i+n)%a.Length])
	modifies a
	{
		// leading assignment + contract frame + strengthen postcondition
		q := a[..];
		index := LeftRotate2(a,n,q);
		LemmaStrengthenPostcondition1(a,q,n,index);
	}

method LeftRotate2(a: array<int>, n: nat, q: seq<int>) returns (index: nat)
	requires a.Length != 0
	requires q == a[..]
	ensures Inv(a[..],q,n,index)
	ensures !Guard(a,index)
	modifies a
	{
		// sequential compostion
		index := Init(a,n,q);
		index := Loop(a,q,n,index);
	}

method Init(a: array<int>, n: nat, q: seq<int>) returns (index: nat)
	requires a.Length != 0 
	requires q == a[..]
	ensures Inv(a[..],q,n,index)
	{
		//assignment
		LemmaInit(a,n,q);
		index := 0;
	}

lemma LemmaInit(a: array<int>, n: nat, q: seq<int>)
	requires a.Length != 0
	requires q == a[..]
	ensures Inv(a[..],q,n,0)
	{}

method Loop(a: array<int>, q: seq<int>, n: nat, index0: nat) returns (index: nat)
	requires Inv(a[..],q,n,index0)
	ensures Inv(a[..],q,n,index)
	ensures !Guard(a,index)
	modifies a
	{
		index := index0;
		// iteration
		while Guard(a,index)
			invariant Inv(a[..],q,n,index)
			decreases V(a,index)
			{
				index := LoopBody(a,q,n,index);
			}
	}

predicate Inv(updated: seq<int>, q: seq<int>, n: nat, index: nat)
{
	|updated| != 0
	&& |q| == |updated|
	&& index <= |q|
	&& forall i :: 0 <= i < index ==> updated[i] == q[(i+n)%|q|]
}

function V(a: array<int>, index: nat): int
{
	a.Length - index
}
predicate method Guard(a: array<int>, index: nat)
{
	index < a.Length
}

method LoopBody(a: array<int>, q: seq<int>, n: nat, index0: nat) returns (index: nat)
	requires Inv(a[..],q,n,index0)
	requires Guard(a,index0)
	ensures Inv(a[..],q,n,index)
	ensures 0 <= V(a,index) < V(a,index0)
	modifies a
	{
		index := index0;
		// assignment
		LemmaUpdate(a,q,n,index);
		a[index], index := q[(index+n)%|q|],index+1;  // ===THE RELEVANT LINE===
	}

lemma LemmaUpdate(a: array<int>, q: seq<int>, n: nat, index: nat)
	requires Inv(a[..],q,n,index)
	requires Guard(a,index)
	ensures Inv(a[..][index := q[(index+n)%|q|]],q,n,index+1)
	ensures index < index+1
{}
	

lemma LemmaStrengthenPostcondition1(a: array<int>, q: seq<int>, n: nat, index: nat)
	requires Inv(a[..],q,n,index)
	requires !Guard(a,index)
	ensures forall i :: 0 <= i < a.Length ==> a[i] == q[(i+n)%|q|]
{}

**Comment by davidcok** [comment] 2020-06-03 01:56
Thanks. I have reproduced on a (much) simpler example. The problem is this:
the right-hand-sides are properly all computed before any assignments are performed,
but the subsequent left-hand-sides can interfere, if one lhs is used within another -- e.g. as in index, a[index] := ... -- the index of the array reference and the array expression (and also the object expression in a o.f expression) must be evaluated before any assignments are made. I see the problem in both cs and java (at least)

**Comment by davidcok** [comment] 2020-06-03 23:35
Fixed in PR 644, for array index assignments, including arrays with multiple dimensions, and for updates to fields.

**Closed** 2020-06-09 16:20 UTC
Labels: bug
