### ISSUE TITLE
It is possible assign a value to an empty type within a function

### ISSUE THREAD

**Issue by G4lvatron** [dafny-lang/dafny#2648] opened 2022-08-29 06:56 UTC
It is possible to give a value to the empty type `Empty` using a let expression. `Empty` should not be able to contain a value though, since no value can satisfy the condition `false`.
```
type Empty = x: int | false witness *

function method broken(): Empty
{
        var r: Empty := 7; // no error, shouldn't be possible?
        r
}

method Main()
{
        var x: Empty := broken();
        print("empty type contains: ");
        print(x);
        assert false;
}
```
The output is `empty type contains: 7` and the code verifies false.
It seems to be only in this specific case where it breaks. In both of the following examples, the verifier correctly says that the value cannot be assigned to `Empty` because it does not satisfy the constraints.
```
function method broken(): Empty
{
        7 // error
}

method broken() returns (r: Empty)
{
        var x: Empty := 7; // error
        r := x;
}
```
This also works properly if the type can contain a value.
```
type MaybeEmpty = x: int | x > 10 witness *

function method broken(): MaybeEmpty
{
        var r: MaybeEmpty := 7; // error
        r
}
```
This looks similar to issue #1958 that I found, but it lacked context as pointed out in the comments.

**Comment by MikaelMayer** [comment] 2022-08-29 16:30
Thanks for reporting this serious issue. You're right, it should be fixed

**Comment by cpitclaudel** [comment] 2022-09-02 22:03
These issues are duplicate of each other.  I propose closing this one and tracking only #1958.  (The problem is that the translation to Boogie introduces a dummy value of the subset type, and Z3 realizes that assuming the existence of this value leads to an inconsistency, thus skipping the check on `:= 7`)

**Closed by cpitclaudel** 2022-09-02 22:03 UTC
Labels: kind: bug, severity: soundness, part: verifier
