### ISSUE TITLE
darrow expected

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#4707] opened 2023-10-23 19:36 UTC
### Dafny version

4.3.0

### Code to produce this issue

```dafny
datatype X = A(i: int) | B(i: int)


method Test(x: X) {
  match x {
    case X.A(i) => print i;
    case X.B(j) => print j;
  }
}
```

### Command to run and resulting output

```code
Paste in VSCode
```

### What happened?

![image](https://github.com/dafny-lang/dafny/assets/3601079/c55b20ca-df53-497c-8df7-28d2ea3dc3f6)

It's weird because elsewhere X.A is valid, except in pattern matching. The pattern matching should either be recognized or the error message a bit less cryptic

### What type of operating system are you experiencing the problem on?

Windows

**Comment by keyboardDrummer** [comment] 2024-04-24 12:32
Closing because this is a duplicate of https://github.com/dafny-lang/dafny/issues/5009

**Closed by keyboardDrummer** 2024-04-24 12:32 UTC
Labels: kind: bug, area: error-reporting, makes-mikael-grateful
