### ISSUE TITLE
Publishing Runtime Library on Maven Central?

### ISSUE THREAD

**Issue by DavePearce** [dafny-lang/dafny#2290] opened 2022-06-23 02:28 UTC
Hi,

I'm wondering whether the `DafnyRuntime.jar` library is published anywhere on Maven central?  After a quick look, I couldn't see it.  If not, is this something that would be of interest to people?

**Comment by keyboardDrummer** [comment] 2022-06-23 12:52
I think it's not. It's something that should be published by the `dafny-lang/dafny` repository, but it's not yet doing that.

**Comment by DavePearce** [comment] 2022-06-26 21:33
Hey --- thanks.  Looks like its a duplicate also of a much earlier issue (https://github.com/dafny-lang/dafny/issues/492) by @robin-aws.  I guess that means its unlikely to go on Maven Central in the near future then?

**Comment by robin-aws** [comment] 2022-09-22 17:47
Hi @DavePearce! I can't comment on any specific date but multiple users are still asking for it, and we are now publishing the .NET `DafnyRuntime.dll` to NuGet, so it's only a matter of time before we get to Java as well.

Closing as duplicate of #492, please do comment on that issue instead as needed!

**Closed by robin-aws** 2022-09-22 17:47 UTC
Labels: kind: enhancement, part: runtime
