### ISSUE TITLE
parser crash on lambda taking a function from a nonexistent type 

### ISSUE THREAD

**Issue by erniecohen** [dafny-lang/dafny#2115] opened 2022-05-07 17:38 UTC
The following triggers "Internal Error - System.InvalidOperationException: Sequence contains no elements" on 3.5.0.40314.
```
function f():() { (x:S->())=>() }
```

**Comment by erniecohen** [comment] 2022-05-07 17:42
I recommend regular fuzz testing. (Or better, prove that Dafny doesn't crash.)

**Comment by cpitclaudel** [comment] 2022-05-07 19:57
Duplicate of https://github.com/dafny-lang/dafny/issues/2104

**Comment by cpitclaudel** [comment] 2022-05-07 19:57
> (Or better, prove that Dafny doesn't crash.)

Working on it :)

**Closed by cpitclaudel** 2022-05-07 19:57 UTC
