### ISSUE TITLE
(soundness) datatype habitation checks don't check const fields

### ISSUE THREAD

**Issue by erniecohen** [dafny-lang/dafny#1182] opened 2021-04-13 18:26 UTC
The following verifies in 3.0:
```
type V = v:nat | false witness *
datatype T = T() {
    const v:V
}
function f():V ensures false {
    var t:T := T();
    t.v
}
```

**Comment by RustanLeino** [comment] 2021-04-16 18:57
Duplicate of issue https://github.com/dafny-lang/dafny/issues/1148 and fixed in https://github.com/dafny-lang/dafny/pull/1149.

**Closed by RustanLeino** 2021-04-16 18:57 UTC
