### ISSUE TITLE
Dafny crashes if an abstract module contains a field `Keys` whose type is not `Set`

### ISSUE THREAD

**Issue by cpitclaudel** [dafny-lang/dafny#1749] opened 2022-01-21 05:44 UTC
Here's a repro:

```
abstract module M {
  const Keys: bool
}
```

and a backtrace:

```
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'Microsoft.Dafny.UserDefinedType' to type 'Microsoft.Dafny.SetType'.
   at Microsoft.Dafny.Translator.GetReadonlyField(Field f) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/Dafny/Verifier/Translator.cs:line 9427
   at Microsoft.Dafny.Translator.AddClassMembers(TopLevelDeclWithMembers c, Boolean includeAllMethods) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/Dafny/Verifier/Translator.cs:line 2204
   at Microsoft.Dafny.Translator.AddTypeDecl(RevealableTypeDecl d) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/Dafny/Verifier/Translator.cs:line 1145
   at Microsoft.Dafny.Translator.DoTranslation(Program p, ModuleDefinition forModule) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/Dafny/Verifier/Translator.cs:line 745
   at Microsoft.Dafny.Translator.Translate(Program p, ErrorReporter reporter, TranslatorFlags flags)+MoveNext() in /Users/salkeldr/Documents/GitHub/dafny-release/Source/Dafny/Verifier/Translator.cs:line 816
   at Microsoft.Dafny.DafnyDriver.Translate(Program dafnyProgram)+MoveNext() in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyDriver/DafnyDriver.cs:line 338
   at Microsoft.Dafny.DafnyDriver.Boogie(String baseName, IEnumerable`1 boogiePrograms, String programId, Dictionary`2& statss, PipelineOutcome& oc) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyDriver/DafnyDriver.cs:line 392
   at Microsoft.Dafny.DafnyDriver.ProcessFiles(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyDriver/DafnyDriver.cs:line 285
   at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyDriver/DafnyDriver.cs:line 53
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass1_0.<Main>b__0() in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyDriver/DafnyDriver.cs:line 34
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by robin-aws** [comment] 2022-07-25 23:08
Dupe of https://github.com/dafny-lang/dafny/issues/1587

**Closed** 2022-07-25 23:09 UTC
Labels: kind: bug, severity: crash
