### ISSUE TITLE
runtime quantification needs a guard checking subtype predicate

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#698] opened 2020-07-02 14:51 UTC
This code verifies but crashes at runtime. Problem is the runtime implementation of the quantification does not guard the check of the quantifier body by the predicate defining the subtype.

```dafny
type Small = x: int | 0 <= x < 100 && x != 3

function method F(x: int): int
  requires x != 3
{
  if x == 3 then 1/0 else 100
}

method Main() {
  var b := forall n: Small :: F(n) == 100;
  print b, "\n";
}
```

**Comment by acioc** [comment] 2020-07-08 20:42
Related to https://github.com/dafny-lang/dafny/issues/697

**Comment by RustanLeino** [comment] 2021-02-05 19:54
Here is an additional test case, which causes the Java and Go compilers to produce malformed code.

``` dafny
newtype byte = x | -128 <= x < 128

method ByteIndexedArray(s: array<int>) returns (rev: array<int>)
  requires s.Length < 128
{
  rev := new int[s.Length];
  forall i: byte | 0 <= i < s.Length as byte {
    rev[i] := s[s.Length as byte - i - 1];
  }
}

method Main() {
  var s := new int[] [40, 41, 42, 43];
  var rev := ByteIndexedArray(s);
  print s[..], " ", rev[..], "\n";
}
```

**Comment by robin-aws** [comment] 2021-09-29 22:22
Duplicate of #697 (but I've copied over the examples as additional test cases)

**Closed** 2021-09-29 22:32 UTC
Labels: soundness, resolution
