### ISSUE TITLE
Feature request: auto-casting {:nativeType} types to their basetypes

### ISSUE THREAD

**Issue by tjhance** [dafny-lang/dafny#325] opened 2019-07-20 02:58 UTC
I've been writing code that uses a lot of `newtype`s, but the need to explicitly cast to the base type using `as` syntax is fairly cumbersome and clutters the code. It seems like it ought to be fairly straightforward to make a `newtype` a subtype of its base type.

In particular, I'm using `nativeType` so that the compiled code will use native integer types instead of big integers, but it's much easier to just use `int` for ghost code. As such, I have to pass back and forth between the two fairly often.

```
newtype{:nativeType "ulong"} uint64 = i:int | 0 <= i < 0x10000000000000000
```

I can imagine scenarios where requiring an explicit cast is a good thing: since I'm using nativeType, a cast would actually correspond to a representation-change in the compiled code, and I might prefer to make that explicit. But I don't see any downside to auto-casting in ghost code.

I did try using a `type` declaration

```
type{:nativeType "ulong"} uint64 = i:int | 0 <= i < 0x10000000000000000
```

which allow auto-casting but doesn't seem to respect the `nativeType` field. Perhaps the best fix would be to support `nativeType` for such types?

**Comment by acioc** [comment] 2020-08-05 21:16
We should document this behavior and explain why

**Comment by davidcok** [comment] 2020-11-13 01:56
Additional text added to the RM - PR 916.

**Comment by atomb** [comment] 2022-05-09 19:04
I think this text pretty clearly articulates why `{:nativeType}` is allowed on `newtype` but not `type`:

https://github.com/dafny-lang/dafny/blob/b22cb6bdc87be4e38f48e7fefb4cab61b79726be/docs/DafnyRef/Types.md?plain=1#L1482-L1487

When combined with @davidcok's text, does that cover everything that needs to be documented here?

**Comment by cpitclaudel** [comment] 2022-05-09 20:43
Documented, yes; but the original request was to allow auto-casting in ghost code, which seems safe.
The problem is that it would introduce more discrepancies between ghost and non-ghost code; maybe that's a bit scary?

**Comment by tjhance** [comment] 2022-05-09 20:57
I didn't really understand the full rationale for `newtype` back when I made this post, so my suggestion probably wasn't that great 😅

**Comment by cpitclaudel** [comment] 2022-05-09 22:10
Thanks for clarifying @tjhance!  Closing for now, and let's revisit this if someone else perks up in this thread :)

**Closed by cpitclaudel** 2022-05-09 22:10 UTC
Labels: documentation
