### ISSUE TITLE
`Expect` not allowed in function methods?

### ISSUE THREAD

**Issue by hmijail** [dafny-lang/dafny#1352] opened 2021-08-16 06:13 UTC
Dafny 3.2.0.30713 (b96750a1cbf4a084ed61b345ff68b42dca13759e)

I'm following the [Expect example in the Dafny Documentation](https://dafny-lang.github.io/dafny/DafnyRef/DafnyRef#sec-expect-statement), but changing the methods for function methods. Expect then causes an error.
The error message doesn't seem to make sense in the context.

example.dfy:
```dafny
function method {:external} fm(b: int): int

predicate method pm(a: int)
{
    true
}

function method fm'(n: int): int
ensures pm(n)
{
    var v := fm(n);
    //assert pm(v);   // OK
    //assume pm(v);   // OK
    expect pm(v);   // error
    v
}
```

```bash
dafny example.dfy 
XXX/example.dfy(14,4): Error: expect statement is not allowed in this context (because this is a ghost method or because the statement is guarded by a specification-only expression)
1 resolution/type errors detected in example.dfy
```

**Comment by robin-aws** [comment] 2021-08-23 21:49
This is by design, although I agree the error message could be clearer in this case.

The use of `expect` can cause a method to halt without producing a value, so it cannot be used to define a function. Here's a motivating example from `dafny0/ResolutionErrors.dfy`:

```dafny
  function UnsafeDivide(a: int, b: int): int {
    expect b != 0;  // expect statement is not allowed in this context
    a / b
  }
```

If expect was allowed here, you would have a partial function masquerading as a total function, which would invalidate specifications that use it.

I think we could both clarify the error message here and comment in the reference manual that `expect` cannot be used in functions, including `function method`s.

**Comment by hmijail** [comment] 2021-08-23 23:01
Aha, thank you for the explanation.

And what about the method in a function-by-method: would `expect` be allowed there? Sounds to me like the same reasoning would forbid it there, but I hope I'm wrong :)

**Comment by robin-aws** [comment] 2021-08-24 02:01
Funny you mention that: https://github.com/dafny-lang/dafny/issues/1376 :)

**Comment by davidcok** [comment] 2022-10-11 00:35
cf. #1434

**Comment by RustanLeino** [comment] 2023-05-01 18:31
I had a sobering thought about the use of `expect` in a function! To support it would require a good bit of change to the machinery that generates function axioms. The function

``` dafny
function F(): int {
  assume false;
  1 + F()
}
```

generates into Boogie a definition axiom like

``` boogie
axiom F() == 1 + F();
```

(I simplified it slightly.) So, even without ever calling `F()`, one gets to assume `false` in the proof context. (In my simplified example, it seems dead easy to make use of this axiom to derive `false`, but it's trickier to do in practice without including a call to `F()`. Nevertheless, generating such an axiom, whether or not the verifier thinks of using it, is a soundness violation.)

The example above uses an `assume`, and we know that `assume` statements are unsound. This is documented and checked, so the behavior above is exactly what we intend.

Now, consider replacing the `assume` above with an `expect`, like

``` dafny
function G(): int {
  expect false;
  1 + G()
}
```

To the verifier, an `expect` is just like an `assume`, which suggests that the translation into Boogie of `G` would be completed analogous to that of `F`. But the `expect` statement is not flagged like an `assume`, because `expect` is explicitly requesting halting behavior at run time and trading it for an assumption during verification. Thus, by just including function `G()` in a program, one would be able to infer `false` even without ever calling `G()`. That's bad.

To fix this in the definition axiom would take some work. I don't think it's worth it. Instead, I'm changing my mind about calling the absence of `expect`s in functions a bug. Indeed, I now think Dafny is doing the right thing to forbid `expect` in functions (and thus, probably also forbidding `expect` in any expression).

**Comment by davidcok** [comment] 2023-05-01 22:03
Closing this issue as something that will not be implemented.

**Closed by davidcok** 2023-05-01 22:03 UTC
Labels: kind: enhancement
