### ISSUE TITLE
ambiguity in tutorial exercise 4

### ISSUE THREAD

**Issue by lgwagner** [dafny-lang/dafny#2102] opened 2022-05-06 16:12 UTC
I'm working through the tutorial found here: https://dafny-lang.github.io/dafny/OnlineTutorial/guide

In exercise 4 I wrote the following code:

![image](https://user-images.githubusercontent.com/2699181/167169825-bd21aed5-2c20-4d4b-bfde-6fbb9be0d7ef.png)

Given the language in the tutorial, I expected to see an error however I did not. The var created on line 7 is inferred to be a ghost variable. I believe the tool is behaving correctly but it took me a bit (and had to ask some questions) to appreciate the nuance. Perhaps the tutorial could be updated to make it clearer. I changed my example to the following and that makes the limitations of functions clearer in the IDE.

![image](https://user-images.githubusercontent.com/2699181/167170243-6376902f-3910-42df-8172-e064441961dd.png)

**Comment by cpitclaudel** [comment] 2022-05-06 20:55
Great catch, thanks!  We should clarify that you cannot `print` or `return` the result of a `function`, even though you can in fact assign it to a(n automatically) ghost variable

**Comment by davidcok** [comment] 2022-07-14 19:38
Postponing this fix until we can explain it with Dafny 4 syntax

**Comment by davidcok** [comment] 2022-11-20 23:22
Duplicate of #1646. Closed on that account. Being fixed by #3085

**Closed by davidcok** 2022-11-20 23:22 UTC
Labels: kind: enhancement, part: documentation
