### ISSUE TITLE
/runAllTests exception

### ISSUE THREAD

**Issue by hmijail** [dafny-lang/dafny#3361] opened 2023-01-13 04:16 UTC
### Dafny version

3.10

### Code to produce this issue

```dafny
method {:test} a(b: bool) {}
```

### Command to run and resulting output

```code
$ dafny reduced.dfy /runAllTests:1 /noVerify /compile:4

Dafny program verifier did not attempt verification
Unhandled exception. System.AggregateException: One or more errors occurred. (Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index'))
 ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Microsoft.Dafny.Compilers.SinglePassCompiler.TrCallStmt(CallStmt s, String receiverReplacement, ConcreteSyntaxTree wr) in /Users/mija/repos/dafny/dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 4279
   at Microsoft.Dafny.Compilers.SinglePassCompiler.TrStmt(Statement stmt, ConcreteSyntaxTree wr, ConcreteSyntaxTree wStmts) in /Users/mija/repos/dafny/dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 3069
   at Microsoft.Dafny.Compilers.SinglePassCompiler.TrStmtList(List`1 stmts, ConcreteSyntaxTree writer) in /Users/mija/repos/dafny/dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 4417
   at Microsoft.Dafny.Compilers.SinglePassCompiler.TrStmt(Statement stmt, ConcreteSyntaxTree wr, ConcreteSyntaxTree wStmts) in /Users/mija/repos/dafny/dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 3073
   at Microsoft.Dafny.Compilers.CsharpCompiler.EmitHaltRecoveryStmt(Statement body, String haltMessageVarName, Statement recoveryBody, ConcreteSyntaxTree wr) in /Users/mija/repos/dafny/dafny/Source/DafnyCore/Compilers/Compiler-Csharp.cs:line 3440
   at Microsoft.Dafny.Compilers.SinglePassCompiler.TrStmt(Statement stmt, ConcreteSyntaxTree wr, ConcreteSyntaxTree wStmts) in /Users/mija/repos/dafny/dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 3386
   at Microsoft.Dafny.Compilers.SinglePassCompiler.TrStmtList(List`1 stmts, ConcreteSyntaxTree writer) in /Users/mija/repos/dafny/dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 4417
   at Microsoft.Dafny.Compilers.SinglePassCompiler.CompileMethod(Program program, Method m, IClassWriter cw, Boolean lookasideBody) in /Users/mija/repos/dafny/dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 2477
   at Microsoft.Dafny.Compilers.SinglePassCompiler.CompileClassMembers(Program program, TopLevelDeclWithMembers c, IClassWriter classWriter) in /Users/mija/repos/dafny/dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 2037
   at Microsoft.Dafny.Compilers.SinglePassCompiler.Compile(Program program, ConcreteSyntaxTree wrx) in /Users/mija/repos/dafny/dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 1423
   at Microsoft.Dafny.DafnyDriver.CompileDafnyProgram(Program dafnyProgram, String dafnyProgramName, ReadOnlyCollection`1 otherFileNames, Boolean invokeCompiler, TextWriter outputWriter) in /Users/mija/repos/dafny/dafny/Source/DafnyDriver/DafnyDriver.cs:line 681
   at Microsoft.Dafny.DafnyDriver.Compile(String fileName, ReadOnlyCollection`1 otherFileNames, Program dafnyProgram, PipelineOutcome oc, IDictionary`2 moduleStats, Boolean verified) in /Users/mija/repos/dafny/dafny/Source/DafnyDriver/DafnyDriver.cs:line 554
   at Microsoft.Dafny.DafnyDriver.ProcessFilesAsync(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId) in /Users/mija/repos/dafny/dafny/Source/DafnyDriver/DafnyDriver.cs:line 358
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args) in /Users/mija/repos/dafny/dafny/Source/DafnyDriver/DafnyDriver.cs:line 123
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass10_0.<Main>b__0() in /Users/mija/repos/dafny/dafny/Source/DafnyDriver/DafnyDriver.cs:line 100
   at System.Threading.Thread.StartCallback()
/Users/mija/bin/dafny: line 34: 17023 Abort trap: 6           "$DOTNET" "$DAFNY" "$@"
```

### What happened?

When a `{:test}` method has any argument and is compiled with `/runAllTests:1`, compilation fails.

This failure doesn't happen with /runAllTests:0.

Maybe it makes sense to reject the code anyway, but an error message would be useful. I figured I'd report this because it caused me some head scratching.

FYI: I was able to use the [creduce tool](https://github.com/csmith-project/creduce) to reduce my original big file into this reproduction case.

### What type of operating system are you experiencing the problem on?

Mac

**Comment by MikaelMayer** [comment] 2023-08-16 14:15
I can't reproduce this bug. Must have been fixed in the meanwhile. I can't go back in time long enough to reproduce the failure as well, so I'm closing it for now. But looks like the test for detecting arguments in method tests was there since April 2022
https://github.com/dafny-lang/dafny/pull/2005

**Closed by MikaelMayer** 2023-08-16 14:15 UTC
Labels: kind: bug
