### ISSUE TITLE
Flaky CI cancelled before completing

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#5530] opened 2024-06-05 15:47 UTC
We did not have an issue to log these. Happened here today
https://github.com/dafny-lang/dafny/actions/runs/9385655091/job/25844369711?pr=5511

**Comment by keyboardDrummer** [comment] 2024-06-05 15:50
Duplicate of https://github.com/dafny-lang/dafny/issues/5488

**Closed by keyboardDrummer** 2024-06-05 15:50 UTC
